name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup .NET 3.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build 3.x
      run: dotnet build -f netcoreapp3.1 --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal